[project]
name = "consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "delta-spark~=3.3.0",
    "pyspark~=3.5.0",
    "ruff>=0.11.9",
]
